### ISSUE TITLE
MusicStore SPA does not build with the latest TypeScript and latest node

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/MusicStore#416]
1. Install VS 2015 CTP6
2. Install node v0.12.0
3. Run `build` in the MusicStore folder. 

Result:

```
[13:05:35][Step 1/1]  [4mRunning "tsng:dev" (tsng) task [24m

[13:06:00][Step 1/1] 

[13:06:00][Step 1/1]  [4mRunning "typescript:dev" (typescript) task [24m

[13:06:19][Step 1/1] File  [36mC:\BuildAgent\work\8b7aec77da8ff11d\MusicStore\src\MusicStore.Spa\wwwroot\js\MusicStore.Store.js [39m created.

[13:06:19][Step 1/1] js: 1 file, map: 0 files, declaration: 0 files (18308ms)

[13:06:27][Step 1/1]  [33mWarning: Task "typescript:dev" failed.  Use --force to continue. [39m

[13:06:27][Step 1/1] 

[13:06:27][Step 1/1]  [31mAborted due to warnings. [39m

[13:06:27][Step 1/1] warn: Exit code 3 from cmd

[13:06:27][Step 1/1] verbose: Stack trace: 

[13:06:27][Step 1/1]    at View35abe795c7c44c9d8e4fd77ba3bf0618.<RenderViewLevel0>b__51() in c:\BuildAgent\temp\buildTmp\65462ffbba064fa5bca6c51f6f5b2f27-1.cs:line 3597

[13:06:27][Step 1/1]    at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)

[13:06:27][Step 1/1]    at Sake.Engine.Builder.BuilderBase`1.StartingTarget(String name)

[13:06:27][Step 1/1]    at View35abe795c7c44c9d8e4fd77ba3bf0618.<RenderViewLevel0>b__42() in c:\BuildAgent\temp\buildTmp\65462ffbba064fa5bca6c51f6f5b2f27-1.cs:line 1259

[13:06:27][Step 1/1]    at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)

[13:06:27][Step 1/1]    at Sake.Engine.Builder.BuilderBase`1.StartingTarget(String name)

[13:06:27][Step 1/1]    at View35abe795c7c44c9d8e4fd77ba3bf0618.<RenderViewLevel0>b__43() in c:\BuildAgent\temp\buildTmp\65462ffbba064fa5bca6c51f6f5b2f27-1.cs:line 1276

[13:06:27][Step 1/1]    at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)

[13:06:27][Step 1/1]    at Sake.Engine.Builder.BuilderBase`1.StartingTarget(String name)

[13:06:27][Step 1/1]    at View35abe795c7c44c9d8e4fd77ba3bf0618.<RenderViewLevel0>b__44() in c:\BuildAgent\temp\buildTmp\65462ffbba064fa5bca6c51f6f5b2f27-1.cs:line 1293

[13:06:27][Step 1/1]    at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)

[13:06:27][Step 1/1]    at Sake.Engine.Builder.BuilderBase`1.StartingTarget(String name)

[13:06:27][Step 1/1]    at View35abe795c7c44c9d8e4fd77ba3bf0618.<RenderViewLevel0>b__45() in c:\BuildAgent\temp\buildTmp\65462ffbba064fa5bca6c51f6f5b2f27-1.cs:line 1310

[13:06:27][Step 1/1]    at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)

[13:06:27][Step 1/1]    at View35abe795c7c44c9d8e4fd77ba3bf0618.<RenderViewLevel0>b__3d() in c:\BuildAgent\temp\buildTmp\65462ffbba064fa5bca6c51f6f5b2f27-1.cs:line 1166

[13:06:27][Step 1/1]    at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)

[13:06:27][Step 1/1]    at Sake.Engine.SakeEngine.Execute(Options options)

[13:06:27][Step 1/1]    at Sake.Engine.SakeEngine.Execute(String[] args)

[13:06:27][Step 1/1]    at Sake.Program.Main(String[] args)

[13:06:28][Step 1/1] Process exited with code 1

[13:06:28][Step 1/1] Step MusicStore (Command Line) failed
```

If you revert back to node 0.10.29 like we have on the CI machines, everything works.

**Comment by victorhurdugaci** [comment]
Can we please address this? It is really bad because you cannot use the latest node & typescript
@DamianEdwards @suhasj

**Comment by muratg** [comment]
@suhasj Victor will be temporarily disabling this.  Could you fix this soon and reenable?

**Comment by victorhurdugaci** [comment]
I managed to get the right version of node and TS. I will not disable it

**Comment by Eilon** [comment]
The SPA project has been removed from this repo (in the dev branch). See https://github.com/aspnet/MusicStore/issues/537 for more info.
