### ISSUE TITLE
beta8 build error

### ISSUE THREAD

**Issue by cheers00** [aspnet/MusicStore#552]
I'm getting the following compilation error with VS2015. I get the same error for build.cmd.

I don't see any contract folder at ``System.Threading.Overlapped\4.0.0\lib``` on my computer.

```
Building MusicStore for DNXCore,Version=v5.0
Error: Could not find a part of the path 'C:\Users\chers00\.dnx\packages\System.Threading.Overlapped\4.0.0\lib\contract
\System.Threading.Overlapped.dll'.
fail: Exit code 1 from cmd
fail: Stack trace:
```

**Comment by Eilon** [comment]
@kichalla can you see if you can repro this?

**Comment by JanSichula** [comment]
+1 My setup is Windows 8.1 Pro with ASP.NET 5 Beta 8. I am getting same error when trying to build against CoreCLR but when I switch to Desktop CLR, a different error listed bellow appears.

System.TypeLoadException: Could not load type 'Microsoft.Framework.Configuration.ConfigurationProvider' from assembly 'M
icrosoft.Framework.Configuration, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at Microsoft.Framework.Configuration.CommandLineConfigurationExtensions.AddCommandLine(IConfigurationBuilder configur
ation, String[] args)
   at Microsoft.AspNet.Hosting.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider service
Provider)
   at Microsoft.Dnx.ApplicationHost.Program.ExecuteMain(DefaultHost host, String applicationName, String[] args)
   at Microsoft.Dnx.ApplicationHost.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider service
Provider)
   at Microsoft.Dnx.Host.Bootstrapper.RunAsync(List`1 args, IRuntimeEnvironment env, String appBase, FrameworkName targe
tFramework)
   at Microsoft.Dnx.Host.RuntimeBootstrapper.ExecuteAsync(String[] args, BootstrapperContext bootstrapperContext)
   at Microsoft.Dnx.Host.RuntimeBootstrapper.Execute(String[] args, BootstrapperContext bootstrapperContext)

**Comment by kichalla** [comment]
I am able to repro this...looking at the lock.json file, the file path for the `compile` is incorrect:

![image](https://cloud.githubusercontent.com/assets/6559784/10578151/23af9dee-7625-11e5-9788-df38e3c79975.png)

As a workaround try changing the `System.Runtime.Serialization.Primitives` in dnxcore50 target framework from `4.0.11-beta-23409` to `4.0.11-beta-23225` and try building again...this seems to work fine for me..

**Comment by kichalla** [comment]
@cheers00 @JanSichula while we still investigate the original issue, I have pushed in a regenerated `project.lock.json` file to master branch now...you should now be able to build successfully.

**Comment by kichalla** [comment]
The build should be fixed now. Feel free to re-open the issue if you still see it.

**Comment by smbecker** [comment]
After upgrading to beta8, I am seeing this same exception but while running my application under dnx451 so obviously, the suggested resolution wouldn't have any impact. Any ideas?

**Comment by smbecker** [comment]
Nevermind, I was using beta8-*, which seems to have pulled in an earlier build of the configuration package. It is working now.
