### ISSUE TITLE
Enable and fix E2E tests on CoreCLR on Linux

### ISSUE THREAD

**Issue by cesarbs** [aspnet/MusicStore#553]
Enable:

    "dnxcore50": {
        "dependencies": {
            "System.Data.SqlClient": "4.0.0-beta-*",
            "System.Xml.XmlDocument": "4.0.1-beta-*"
        }
    }

Fix:

    xUnit.net DNX Runner (64-bit DNXCore 5.0)
      Discovering: E2ETests
      Discovered:  E2ETests
      Starting:    E2ETests
        E2ETests.OpenIdConnectTests.OpenIdConnect_OnMono(serverType: Kestrel, runtimeFlavor: Mono, architecture: x86, applicationBaseUrl: "http://localhost:5042/") [SKIP]
          Test cannot run on this runtime framework.
    warning : [Smoke:WebListener:CoreClr:x86] Host process already exited or never started successfully.
    warning : [Publish:WebListener:Clr:x64:False] Host process already exited or never started successfully.
    warning : [Publish:WebListener:Clr:x64:False] Failed to delete directory : Could not find a part of the path '/tmp/ab94e280-c144-cd02-38ad-f01ca7235b85'.
    warning : [Publish:WebListener:Clr:x64:False] Error occured while dropping database 56866285e85f0207bc44686f00e93768. Exception : System.DllNotFoundException: Unable to load DLL 'api-ms-win-core-processthreads-l1-1-0.dll': The specified module could not be found.
     (Exception from HRESULT: 0x8007007E)
       at Interop.mincore.GetCurrentThread()
       at Interop.mincore.OpenThreadToken(TokenAccessLevels desiredAccess, WinSecurityContext openAs, SafeAccessTokenHandle& tokenHandle)
       at System.Security.Principal.WindowsIdentity.GetCurrentToken(TokenAccessLevels desiredAccess, Boolean threadOnly, Boolean& isImpersonating, Int32& hr)
       at System.Security.Principal.WindowsIdentity.GetCurrentInternal(TokenAccessLevels desiredAccess, Boolean threadOnly)
       at System.Data.ProviderBase.DbConnectionPoolIdentity.GetCurrent()
       at System.Data.ProviderBase.DbConnectionPoolGroup.GetConnectionPool(DbConnectionFactory connectionFactory)
       at System.Data.ProviderBase.DbConnectionFactory.GetConnectionPool(DbConnection owningObject, DbConnectionPoolGroup connectionPoolGroup)
       at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
       at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
       at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
       at System.Data.SqlClient.SqlConnection.Open()
       at E2ETests.DbUtils.DropDatabase(String databaseName, ILogger logger)
    warning : [Smoke:WebListener:CoreClr:x86] Error occured while dropping database 4dbaf61e4123ea795601e1371ba5ffbd. Exception : System.DllNotFoundException: Unable to load DLL 'api-ms-win-core-processthreads-l1-1-0.dll': The specified module could not be found.
     (Exception from HRESULT: 0x8007007E)
       at Interop.mincore.GetCurrentThread()
       at Interop.mincore.OpenThreadToken(TokenAccessLevels desiredAccess, WinSecurityContext openAs, SafeAccessTokenHandle& tokenHandle)
       at System.Security.Principal.WindowsIdentity.GetCurrentToken(TokenAccessLevels desiredAccess, Boolean threadOnly, Boolean& isImpersonating, Int32& hr)
       at System.Security.Principal.WindowsIdentity.GetCurrentInternal(TokenAccessLevels desiredAccess, Boolean threadOnly)
       at System.Data.ProviderBase.DbConnectionPoolIdentity.GetCurrent()
       at System.Data.ProviderBase.DbConnectionPoolGroup.GetConnectionPool(DbConnectionFactory connectionFactory)
       at System.Data.ProviderBase.DbConnectionFactory.GetConnectionPool(DbConnection owningObject, DbConnectionPoolGroup connectionPoolGroup)
       at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
       at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
       at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
       at System.Data.SqlClient.SqlConnection.Open()
       at E2ETests.DbUtils.DropDatabase(String databaseName, ILogger logger)
        E2ETests.PublishAndRunTests_OnX64.Publish_And_Run_Tests_On_AMD64(serverType: WebListener, runtimeFlavor: Clr, architecture: x64, applicationBaseUrl: "http://localhost:5025/", noSource: False) [FAIL]
          System.Exception : dnu publish exited with exit code : 2
          Stack Trace:
               at Microsoft.AspNet.Server.Testing.ApplicationDeployer.DnuPublish(String publishRoot)
               at Microsoft.AspNet.Server.Testing.SelfHostDeployer.Deploy()
               at E2ETests.PublishAndRunTests.<Publish_And_Run_Tests>d__0.MoveNext()
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
               at E2ETests.PublishAndRunTests_OnX64.<Publish_And_Run_Tests_On_AMD64>d__0.MoveNext()
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        E2ETests.SmokeTests_OnMono.SmokeTestSuite_OnMono(serverType: Kestrel, runtimeFlavor: Mono, architecture: x86, applicationBaseUrl: "http://localhost:5010/") [SKIP]
          Test cannot run on this runtime framework.
        E2ETests.SmokeTests_X86_Coreclr.SmokeTestSuite_OnX86_coreclr(serverType: WebListener, runtimeFlavor: CoreClr, architecture: x86, applicationBaseUrl: "http://localhost:5005/") [FAIL]
          System.IO.IOException : Broken pipe
          Stack Trace:
               at System.IO.UnixFileStream.SysCall[TArg1,TArg2](Func`4 sysCall, TArg1 arg1, TArg2 arg2, Boolean throwOnError, Boolean ignoreNotSupported)
               at System.IO.UnixFileStream.WriteNative(Byte[] array, Int32 offset, Int32 count)
               at System.IO.UnixFileStream.FlushWriteBuffer()
               at System.IO.UnixFileStream.Flush(Boolean flushToDisk)
               at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
               at Microsoft.AspNet.Server.Testing.SelfHostDeployer.StartSelfHost()
               at Microsoft.AspNet.Server.Testing.SelfHostDeployer.Deploy()
               at E2ETests.SmokeTests.<SmokeTestSuite>d__0.MoveNext()
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
               at E2ETests.SmokeTests_X86_Coreclr.<SmokeTestSuite_OnX86_coreclr>d__0.MoveNext()
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    warning : [Smoke:WebListener:Clr:x86] Retry count 1..
    warning : [Smoke:Kestrel:CoreClr:x86] Retry count 1..
        E2ETests.SmokeTests_OnIIS.SmokeTestSuite_On_IIS_X86(serverType: IIS, runtimeFlavor: Clr, architecture: x86, applicationBaseUrl: "http://localhost:5013/") [SKIP]
          Test cannot run on this operating system.
        E2ETests.SmokeTests_OnIIS.SmokeTestSuite_On_IIS_X86(serverType: IIS, runtimeFlavor: CoreClr, architecture: x64, applicationBaseUrl: "http://localhost:5013/") [SKIP]
          Test cannot run on this operating system.
        E2ETests.PublishAndRunTests_OnX86.Publish_And_Run_Tests_On_Mono(serverType: Kestrel, runtimeFlavor: Mono, architecture: x86, applicationBaseUrl: "http://localhost:5029/", noSource: False) [SKIP]
          Test cannot run on this runtime framework.
        E2ETests.PublishAndRunTests_OnX86.Publish_And_Run_Tests_On_Mono(serverType: Kestrel, runtimeFlavor: Mono, architecture: x86, applicationBaseUrl: "http://localhost:5030/", noSource: True) [SKIP]
          Test cannot run on this runtime framework.
        E2ETests.NtlmAuthenticationTests.NtlmAuthenticationTest(serverType: WebListener, runtimeFlavor: CoreClr, architecture: x64, applicationBaseUrl: "http://localhost:5052/") [SKIP]
          Test cannot run on this operating system.
    warning : [Smoke:Kestrel:CoreClr:x86] Failed to complete the request : An error occurred while sending the request..
    warning : [Smoke:WebListener:Clr:x86] Failed to complete the request : An error occurred while sending the request..
    warning : [Smoke:WebListener:Clr:x86] Host process already exited or never started successfully.
    warning : [Smoke:Kestrel:CoreClr:x86] Host process already exited or never started successfully.
    warning : [Smoke:WebListener:Clr:x86] Error occured while dropping database 627be8cb4b33a822d90d663203ea672d. Exception : System.DllNotFoundException: Unable to load DLL 'api-ms-win-core-processthreads-l1-1-0.dll': The specified module could not be found.
     (Exception from HRESULT: 0x8007007E)
       at Interop.mincore.GetCurrentThread()
       at Interop.mincore.OpenThreadToken(TokenAccessLevels desiredAccess, WinSecurityContext openAs, SafeAccessTokenHandle& tokenHandle)
       at System.Security.Principal.WindowsIdentity.GetCurrentToken(TokenAccessLevels desiredAccess, Boolean threadOnly, Boolean& isImpersonating, Int32& hr)
       at System.Security.Principal.WindowsIdentity.GetCurrentInternal(TokenAccessLevels desiredAccess, Boolean threadOnly)
       at System.Data.ProviderBase.DbConnectionPoolIdentity.GetCurrent()
       at System.Data.ProviderBase.DbConnectionPoolGroup.GetConnectionPool(DbConnectionFactory connectionFactory)
       at System.Data.ProviderBase.DbConnectionFactory.GetConnectionPool(DbConnection owningObject, DbConnectionPoolGroup connectionPoolGroup)
       at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
       at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
       at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
       at System.Data.SqlClient.SqlConnection.Open()
       at E2ETests.DbUtils.DropDatabase(String databaseName, ILogger logger)
    warning : [Smoke:Kestrel:CoreClr:x86] Error occured while dropping database fe5e226f33f7d26d33bf60c0f36277c6. Exception : System.DllNotFoundException: Unable to load DLL 'api-ms-win-core-processthreads-l1-1-0.dll': The specified module could not be found.
     (Exception from HRESULT: 0x8007007E)
       at Interop.mincore.GetCurrentThread()
       at Interop.mincore.OpenThreadToken(TokenAccessLevels desiredAccess, WinSecurityContext openAs, SafeAccessTokenHandle& tokenHandle)
       at System.Security.Principal.WindowsIdentity.GetCurrentToken(TokenAccessLevels desiredAccess, Boolean threadOnly, Boolean& isImpersonating, Int32& hr)
       at System.Security.Principal.WindowsIdentity.GetCurrentInternal(TokenAccessLevels desiredAccess, Boolean threadOnly)
       at System.Data.ProviderBase.DbConnectionPoolIdentity.GetCurrent()
       at System.Data.ProviderBase.DbConnectionPoolGroup.GetConnectionPool(DbConnectionFactory connectionFactory)
       at System.Data.ProviderBase.DbConnectionFactory.GetConnectionPool(DbConnection owningObject, DbConnectionPoolGroup connectionPoolGroup)
       at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
       at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
       at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
       at System.Data.SqlClient.SqlConnection.Open()
       at E2ETests.DbUtils.DropDatabase(String databaseName, ILogger logger)
        E2ETests.SmokeTests_X86_Coreclr.SmokeTestSuite_OnX86_coreclr(serverType: Kestrel, runtimeFlavor: CoreClr, architecture: x86, applicationBaseUrl: "http://localhost:5006/") [FAIL]
          System.OperationCanceledException : Failed to connect, retry canceled.
          Stack Trace:
    warning : [Smoke:Kestrel:Clr:x86] Retry count 1..
               at Microsoft.AspNet.Server.Testing.RetryHelper.<RetryRequest>d__0.MoveNext()
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
               at E2ETests.SmokeTests.<SmokeTestSuite>d__0.MoveNext()
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
               at E2ETests.SmokeTests_X86_Coreclr.<SmokeTestSuite_OnX86_coreclr>d__0.MoveNext()
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        E2ETests.SmokeTests_X86_Clr.SmokeTestSuite_OnX86_clr(serverType: WebListener, runtimeFlavor: Clr, architecture: x86, applicationBaseUrl: "http://localhost:5002/") [FAIL]
          System.OperationCanceledException : Failed to connect, retry canceled.
          Stack Trace:
               at Microsoft.AspNet.Server.Testing.RetryHelper.<RetryRequest>d__0.MoveNext()
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
               at E2ETests.SmokeTests.<SmokeTestSuite>d__0.MoveNext()
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
               at E2ETests.SmokeTests_X86_Clr.<SmokeTestSuite_OnX86_clr>d__0.MoveNext()
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    warning : [Smoke:Kestrel:Clr:x86] Failed to complete the request : An error occurred while sending the request..
    warning : [Smoke:Kestrel:Clr:x86] Host process already exited or never started successfully.
    warning : [Smoke:Kestrel:Clr:x86] Error occured while dropping database 8f465b56ac4b8bc05f2fa48d6882987e. Exception : System.DllNotFoundException: Unable to load DLL 'api-ms-win-core-processthreads-l1-1-0.dll': The specified module could not be found.
     (Exception from HRESULT: 0x8007007E)
       at Interop.mincore.GetCurrentThread()
       at Interop.mincore.OpenThreadToken(TokenAccessLevels desiredAccess, WinSecurityContext openAs, SafeAccessTokenHandle& tokenHandle)
       at System.Security.Principal.WindowsIdentity.GetCurrentToken(TokenAccessLevels desiredAccess, Boolean threadOnly, Boolean& isImpersonating, Int32& hr)
       at System.Security.Principal.WindowsIdentity.GetCurrentInternal(TokenAccessLevels desiredAccess, Boolean threadOnly)
       at System.Data.ProviderBase.DbConnectionPoolIdentity.GetCurrent()
       at System.Data.ProviderBase.DbConnectionPoolGroup.GetConnectionPool(DbConnectionFactory connectionFactory)
       at System.Data.ProviderBase.DbConnectionFactory.GetConnectionPool(DbConnection owningObject, DbConnectionPoolGroup connectionPoolGroup)
       at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
       at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
       at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
       at System.Data.SqlClient.SqlConnection.Open()
       at E2ETests.DbUtils.DropDatabase(String databaseName, ILogger logger)
        E2ETests.SmokeTests_X86_Clr.SmokeTestSuite_OnX86_clr(serverType: Kestrel, runtimeFlavor: Clr, architecture: x86, applicationBaseUrl: "http://localhost:5003/") [FAIL]
          System.OperationCanceledException : Failed to connect, retry canceled.
          Stack Trace:
               at Microsoft.AspNet.Server.Testing.RetryHelper.<RetryRequest>d__0.MoveNext()
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
               at E2ETests.SmokeTests.<SmokeTestSuite>d__0.MoveNext()
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
               at E2ETests.SmokeTests_X86_Clr.<SmokeTestSuite_OnX86_clr>d__0.MoveNext()
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      Finished:    E2ETests
    === TEST EXECUTION SUMMARY ===
       E2ETests  Total: 12, Errors: 0, Failed: 5, Skipped: 7, Time: 2.776s

**Comment by cesarbs** [comment]
This affects https://github.com/aspnet/Universe/issues/304.

**Comment by muratg** [comment]
@kichalla this affects cross plat runs with CoreCLR.  Please have a look at this soon.

**Comment by kichalla** [comment]
@muratg I took a look at this now...Currently E2E tests only run on the `dnx451` TFM, but the actual tests are run across both `dnx451` and `dnxcore50` TFMs as the tests dynamically launch the dnx processes.  
True that there is still an issue that these tests depend on `dnx451` only which forces to install Mono on `Linux` or `Mac`....but based on @dougbu we currently need Mono always to run our builds...So I think we are good for now?

**Comment by muratg** [comment]
Are we able to run E2E tests on CoreCLR?  I'm not too worried about build needing Mono, but I'd like to see all tests running on CoreCLR so that we can find issues before customers.

**Comment by kichalla** [comment]
@muratg As discussed offline, in general we are able to run E2E tests on CoreClr. The tests related to OpenIdConnect are currently failing, but they fail both in desktop and coreclr and need to be updated to reflect the behavior changes that happened in OpenIdConnect space. There is already another issue tracking this https://github.com/aspnet/MusicStore/issues/565, so we can close this issue

**Comment by muratg** [comment]
If the runs on CoreCLR are green we can close it, otherwise let's keep it open until we get green on CI.

**Comment by kichalla** [comment]
This issue is fixed except for one test case. More details below:

The tests now run on CoreClr. i.e the tests run on CoreClr and launch servers of different flavors (kestrel + mono, kestrel + clr, kestrel + coreclr etc.).

After changing the tests to run on CoreClr, we hit following issues related to HttpClient:
https://github.com/dotnet/corefx/issues/4945
https://github.com/dotnet/corefx/issues/4960

The following scenario currently fails and so has been disabled(Note that I cannot repro it on my VM which has 4.2.1 version of Mono compared to 4.0.5 version on Travis CI):
Tests type: Smoke Tests
Client: CoreClr
Server: Kestrel + Mono
