### ISSUE TITLE
ArgumentException when trying to remove item from cart

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/MusicStore#568]
1. Host MusicStore and browse to it
2. Click on Register
3. Go to the Store and add any item to Cart
4. Remove item from Cart
5. Get below exception

```
fail: Microsoft.AspNet.Diagnostics.ExceptionHandlerMiddleware[0]
      An unhandled exception has occurred: The cookie token must be provided.
      Parameter name: antiforgeryTokenSet
      System.ArgumentException: The cookie token must be provided.
      Parameter name: antiforgeryTokenSet
         at Microsoft.AspNet.Antiforgery.DefaultAntiforgery.ValidateTokens(HttpContext context, AntiforgeryTokenSet antiforgeryTokenSet)
         at MusicStore.Controllers.ShoppingCartController.<RemoveFromCart>d__10.MoveNext() in C:\MusicStore\Controllers\ShoppingCartController.cs:line 78
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.Mvc.Controllers.ControllerActionExecutor.<CastToObject>d__8`1.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
```

**Comment by ryanbrandenburg** [comment]
Hey @BrennanConroy, this sounds like what I fixed in https://github.com/aspnet/Antiforgery/pull/21 Double check that you've got the latest Antiforgery bits from dev.

**Comment by BrennanConroy** [comment]
Oh maybe, I found this when testing RC1 bits

**Comment by BrennanConroy** [comment]
Yep that fixed it
