### ISSUE TITLE
Sequence contains no elements when running under stress

### ISSUE THREAD

**Issue by anpete** [aspnet/MusicStore#635]
Running a stress scenario with 10 clients, we sometimes get:

```
fail: Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler[1]
      An exception occurred in the database while iterating the results of a query.
      System.InvalidOperationException: Sequence contains no elements
         at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
         at lambda_method(Closure , QueryContext )
         at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass19_1`1.<CompileQuery>b__1(QueryContext qc)
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at lambda_method(Closure , QueryContext )
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass19_1`1.<CompileQuery>b__1(QueryContext qc)
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[0]
      An unhandled exception has occurred: Sequence contains no elements
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at lambda_method(Closure , QueryContext )
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass19_1`1.<CompileQuery>b__1(QueryContext qc)
   at MusicStore.Models.ShoppingCart.RemoveFromCart(Int32 id) in C:\Dev\github\aspnet\MusicStore\src\MusicStore\Models\ShoppingCart.cs:line 57
   at MusicStore.Controllers.ShoppingCartController.<RemoveFromCart>d__7.MoveNext() in C:\Dev\github\aspnet\MusicStore\src\MusicStore\Controllers\ShoppingCartController.cs:line 80
```

Could be a race condition where two clients are hitting RemoveFromCart at the same time.

**Comment by Eilon** [comment]
@anpete so we suspect it's a bug in MusicStore itself and not EF?

**Comment by anpete** [comment]
@Eilon Correct. The query needs to use SingleOrDefault in case the cart item doesn't exist - It may have been deleted by another request, or could just be a spurious id. I've been meaning to send a PR for this.

**Comment by Eilon** [comment]
Great!

**Comment by DavidObando** [comment]
#662

**Comment by anpete** [comment]
Looks like @DavidObando beat me too it :smile:
