### ISSUE TITLE
Consistent failed test  SmokeTests_X64.WindowsOS

### ISSUE THREAD

**Issue by troydai** [aspnet/MusicStore#673]
```
Test:
SmokeTests_X64.WindowsOS(serverType: IISExpress, runtimeFlavor: CoreC…icationType: Standalone, applicationBaseUrl: "http://localhost:5019/")

Assert.Equal() Failure
Expected: OK
Actual:   BadGateway
   at E2ETests.Validator.<VerifyHomePage>d__17.MoveNext() in D:\b\work\35116a8defcd3a21\Universe\MusicStore\test\E2ETests\Implementation\Validator.cs:line 88
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at E2ETests.SmokeTestHelper.<RunTestsAsync>d__0.MoveNext() in D:\b\work\35116a8defcd3a21\Universe\MusicStore\test\E2ETests\SmokeTestHelper.cs:line 36
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at E2ETests.SmokeTests.<SmokeTestSuite>d__2.MoveNext() in D:\b\work\35116a8defcd3a21\Universe\MusicStore\test\E2ETests\SmokeTests.cs:line 207
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at E2ETests.SmokeTests_X64.<WindowsOS>d__2.MoveNext() in D:\b\work\35116a8defcd3a21\Universe\MusicStore\test\E2ETests\SmokeTests.cs:line 100
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

```

**Comment by cesarbs** [comment]
cc @BrennanConroy @JunTaoLuo

**Comment by cesarbs** [comment]
Re-enable tests when fixed.

**Comment by JunTaoLuo** [comment]
Failures seemed to have been caused by https://github.com/aspnet/KestrelHttpServer/issues/866

**Comment by halter73** [comment]
This should now be fixed.

**Comment by Eilon** [comment]
So we can close this?

**Comment by JunTaoLuo** [comment]
@Eilon, we still need to turn the tests back on and verify the fix.

**Comment by JunTaoLuo** [comment]
re-enabled in https://github.com/aspnet/MusicStore/commit/149fbfa99a674e560712adf39efef45a009167a1
