### ISSUE TITLE
Patch: [Flaky test]

### ISSUE THREAD

**Issue by pranavkm** [aspnet/MusicStore#779]
SmokeTests_X64.WindowsOS(serverType: IISExpress, runtimeFlavor: CoreC…plicationType: Portable, applicationBaseUrl: "http://localhost:5018/") 

```
System.Net.Http.HttpRequestException : An error occurred while sending the request.
---- System.Net.Http.WinHttpException : The operation timed out
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at E2ETests.Validator.<DoPostAsync>d__15.MoveNext() in C:\BuildAgent\work\d6337ac2abf63a4b\.repositories\MusicStore\test\E2ETests\Implementation\Validator.cs:line 58
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at E2ETests.Validator.<LoginWithGoogle>d__1.MoveNext() in C:\BuildAgent\work\d6337ac2abf63a4b\.repositories\MusicStore\test\E2ETests\Implementation\GoogleLoginScenarios.cs:line 63
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at E2ETests.SmokeTestHelper.<RunTestsAsync>d__0.MoveNext() in C:\BuildAgent\work\d6337ac2abf63a4b\.repositories\MusicStore\test\E2ETests\SmokeTestHelper.cs:line 105
```

**Comment by pranavkm** [comment]
cc @Eilon. @kichalla any guesses why this might be misbehaving?

**Comment by Eilon** [comment]
@kichalla - can you take a look?

**Comment by Eilon** [comment]
Ping? Anything we can/need to do for Preview1?

**Comment by kichalla** [comment]
The tests in preview1 branch of MusicStore have been running fairly stable, so I don't think we need to do something here. We could revisit if we see a similar stack trace in future.

**Comment by kichalla** [comment]
http://aspnetci/viewType.html?buildTypeId=Lite_MusicStoreTest&branch_XPlat=2.0.0-preview1&tab=buildTypeStatusDiv

**Comment by pranavkm** [comment]
This was from the patch branch. If we made recent changes to stabilize this, we should port this over to the patch branches.

**Comment by Eilon** [comment]
Oh patch.. well, I'll park the bug in preview2, but per @pranavkm 's comments, if there's something worth porting to the patch branches we should look at that.

**Comment by kichalla** [comment]
This test has been running stably in 'dev' branch for a while now. We have enough logging to diagnose the issue if it were to break the next time. So I am closing this issue for now.
