### ISSUE TITLE
[Flaky test]: SmokeTestsOnNanoServerUsingStandaloneRuntime.Test(serverType: WebListener, portToListen: 5000, applicationType: Standalone)

### ISSUE THREAD

**Issue by pranavkm** [aspnet/MusicStore#784]
```
Assert.Equal() Failure
                                   (pos 26)
Expected: úúú/projectk-nano:5000/Account/ExternalLoginCallback?ReturnUrl=%úúú
Actual:   úúú/projectk-nano:5000/
                                   (pos 26)
   at E2ETests.Validator.<LoginWithGoogle>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at E2ETests.SmokeTestHelper.<RunTestsAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at E2ETests.SmokeTestsOnNanoServer.<RunTestsAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at E2ETests.SmokeTestsOnNanoServerUsingStandaloneRuntime.<Test>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by kichalla** [comment]
This test has been running stable for a while now. We have enough logging already. We can revisit later if it fails.
