### ISSUE TITLE
Broken tests: DotnetRunTests_X64_Kestrel_CoreClr et al

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/MusicStore#847]
This test [fails](http://aspnetci/viewLog.html?buildId=457039&buildTypeId=Releases_21Public_Win2012) with the following error in 2.1 branches:
```
System.Exception : Command exited unexpectedly with exit code: 1
   at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter[T](Task`1 task, TimeSpan timeout, String filePath, Int32 lineNumber)
   at Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer.StartSelfHostAsync(Uri hintUrl)
   at Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer.DeployAsync()
   at E2ETests.DotnetRunTestRunner.RunTests(ServerType serverType, RuntimeFlavor runtimeFlavor, ApplicationType applicationType, RuntimeArchitecture runtimeArchitecture) in C:\b\w\33bdfc1cae7b2a38\modules\MusicStore\test\MusicStore.E2ETests\DotnetRunTestRunner.cs:line 58
--- End of stack trace from previous location where exception was thrown ---
------- Stdout: -------
| [2018-04-27T11:05:42] TestLifetime Information: Starting test DotnetRunTests_Kestrel_CoreClr_Portable
| [2018-04-27T11:05:42] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Deploying [Variation] :: ServerType=Kestrel, Runtime=CoreClr, Arch=x64, BaseUrlHint=, Publish=False
| [2018-04-27T11:05:42] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Executing dotnet run --no-restore --framework netcoreapp2.1 /p:VerifyMatchingImplicitPackageVersion=false -- --server.urls http://localhost:56268/  --server Microsoft.AspNetCore.Server.Kestrel
| [2018-04-27T11:05:42] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: SET ASPNETCORE_ENVIRONMENT=Development
| [2018-04-27T11:05:42] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: SET ASPNETCORE_DETAILEDERRORS=true
| [2018-04-27T11:05:42] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: SET Data__DefaultConnection__ConnectionString=Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=MusicStore_Test_301e272065b246499eb6f14b42ac3664;Integrated Security=True;MultipleActiveResultSets=True;Connect Timeout=30
| [2018-04-27T11:05:42] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Started dotnet. Process Id : 21784
| [2018-04-27T11:05:43] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: C:\b\w\33bdfc1cae7b2a38\modules\MusicStore\samples\MusicStore\MusicStore.csproj : error : The project was restored using Microsoft.NETCore.App version 2.1.0-rc1-26427-03, but with current settings, version 2.1.0-rc1-26419-02 would be used instead.  To resolve this issue, make sure the same settings are used for restore and for subsequent operations such as build or publish.  Typically this issue can occur if the RuntimeIdentifier property is set during build or publish but not during restore.
| [2018-04-27T11:05:43] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Warning: dotnet stderr: The build failed. Please fix the build errors and run again.
| [2018-04-27T11:05:43] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: host process ID 21784 shut down
| [2018-04-27T11:05:43] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Host process shutting down.
| [2018-04-27T11:05:43] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Warning: Host process already exited or never started successfully.
| [2018-04-27T11:05:43] DotnetRunTests Information: Trying to drop database 'MusicStore_Test_301e272065b246499eb6f14b42ac3664'
| [2018-04-27T11:05:43] DotnetRunTests Information: Successfully dropped database MusicStore_Test_301e272065b246499eb6f14b42ac3664
| [2018-04-27T11:05:43] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: [Time]: Total time taken for this test variation '0.9839559' seconds
| [2018-04-27T11:05:43] TestLifetime Information: Finished test DotnetRunTests_Kestrel_CoreClr_Portable in 0.9846652s
```

**Comment by ryanbrandenburg** [comment]
@muratg can we get this for RTM? Our release/2.1 branch tests are failing 100% of the time.
