### ISSUE TITLE
Flaky test: SmokeTests_X64_IISExpress_CoreClr_Portable

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/MusicStore#848]
This test [fails](http://aspnetci/viewLog.html?buildId=459908&buildTypeId=Lite_MusicStoreTest) occasionally with the following error:
```
Assert.Equal() Failure
Expected: OK
Actual:   InternalServerError
   at E2ETests.Validator.VerifyHomePage(HttpResponseMessage response, Boolean useNtlmAuthentication) in C:\b\w\33bdfc1cae7b2a38\modules\MusicStore\test\MusicStore.E2ETests\Implementation\Validator.cs:line 94
   at E2ETests.SmokeTestRunner.RunTestsAsync(DeploymentResult deploymentResult, ILogger logger) in C:\b\w\33bdfc1cae7b2a38\modules\MusicStore\test\MusicStore.E2ETests\SmokeTestRunner.cs:line 85
   at E2ETests.SmokeTestRunner.SmokeTestSuite(ServerType serverType, RuntimeFlavor runtimeFlavor, RuntimeArchitecture architecture, ApplicationType applicationType) in C:\b\w\33bdfc1cae7b2a38\modules\MusicStore\test\MusicStore.E2ETests\SmokeTestRunner.cs:line 59
--- End of stack trace from previous location where exception was thrown ---
------- Stdout: -------
| [2018-05-02T12:22:16] TestLifetime Information: Starting test SmokeTestSuite_IISExpress_Portable
| [2018-05-02T12:22:16] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: Deploying [Variation] :: ServerType=IISExpress, Runtime=CoreClr, Arch=x64, BaseUrlHint=, Publish=True
| [2018-05-02T12:22:16] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: SET ASPNETCORE_ENVIRONMENT=SocialTesting
| [2018-05-02T12:22:16] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: Executing command dotnet publish  --output "C:\b\t\buildTmp\f5ee055e-7598-439f-934b-f85d0b4d3944" --framework netcoreapp2.1 --configuration Release --no-restore -p:VerifyMatchingImplicitPackageVersion=false 
| [2018-05-02T12:22:16] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: dotnet-publish stdout: Microsoft (R) Build Engine version 15.7.172.38367 for .NET Core
| [2018-05-02T12:22:16] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: dotnet-publish stdout: Copyright (C) Microsoft Corporation. All rights reserved.
| [2018-05-02T12:22:17] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: dotnet-publish stdout:   You are working with a preview version of the .NET Core SDK. You can define the SDK version via a global.json file in the current project. More at https://go.microsoft.com/fwlink/?linkid=869452
| [2018-05-02T12:22:17] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: dotnet-publish stdout:   MusicStore -> C:\b\w\33bdfc1cae7b2a38\modules\MusicStore\samples\MusicStore\bin\Release\netcoreapp2.1\MusicStore.dll
| [2018-05-02T12:22:17] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: dotnet-publish stdout:   MusicStore -> C:\b\w\33bdfc1cae7b2a38\modules\MusicStore\samples\MusicStore\bin\Release\netcoreapp2.1\MusicStore.Views.dll
| [2018-05-02T12:22:18] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: dotnet-publish stdout:   MusicStore -> C:\b\t\buildTmp\f5ee055e-7598-439f-934b-f85d0b4d3944\
| [2018-05-02T12:22:18] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: dotnet publish finished with exit code : 0
| [2018-05-02T12:22:18] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: Attempting to start IIS Express on port: 63871
| [2018-05-02T12:22:18] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: Executing command : C:\Program Files\IIS Express\iisexpress.exe /site:MusicStoreTestSite /config:C:\b\t\buildTmp\tmpC549.tmp /trace:error
| [2018-05-02T12:22:18] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: SET ASPNETCORE_ENVIRONMENT=SocialTesting
| [2018-05-02T12:22:18] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: SET ASPNETCORE_DETAILEDERRORS=true
| [2018-05-02T12:22:18] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: SET Data__DefaultConnection__ConnectionString=Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=MusicStore_Test_223a38d182ae4d44b0785cbd7320de9e;Integrated Security=True;MultipleActiveResultSets=True;Connect Timeout=30
| [2018-05-02T12:22:18] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress Process 7364 started
| [2018-05-02T12:22:18] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout: Starting IIS Express ...
| [2018-05-02T12:22:18] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout: Initializing the W3 Server Started CTC = 72009140 
| [2018-05-02T12:22:18] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout: W3 Server initializing WinSock.  CTC = 72009140 
| [2018-05-02T12:22:18] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout: W3 Server WinSock initialized.  CTC = 72009140 
| [2018-05-02T12:22:18] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout: W3 Server ThreadPool initialized (ipm has signalled).  CTC = 72009140 
| [2018-05-02T12:22:18] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout: Start listenerChannel http:0
| [2018-05-02T12:22:18] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout: Successfully registered URL "http://localhost:63871/" for site "MusicStoreTestSite" application "/"
| [2018-05-02T12:22:18] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout: Registration completed for site "MusicStoreTestSite"
| [2018-05-02T12:22:18] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout: AppPool 'IISExpressAppPool' initialized
| [2018-05-02T12:22:18] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout: InitComplete event signalled
| [2018-05-02T12:22:18] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout: IIS Express is running.
| [2018-05-02T12:22:18] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: Started iisexpress successfully. Process Id : 7364, Port: 63871
| [2018-05-02T12:22:18] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: Application ready at URL: http://localhost:63871/
| [2018-05-02T12:22:18] SmokeTestSuite Warning: Retry count 1..
| [2018-05-02T12:22:18] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout: IncrementMessages called
| [2018-05-02T12:22:18] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout: Request started: "GET" http://localhost:63871/
| [2018-05-02T12:22:18] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout: Request ended: http://localhost:63871/ with HTTP status 500.0
| [2018-05-02T12:22:18] SmokeTestSuite Information: Verifying home page
| [2018-05-02T12:22:18] SmokeTestSuite Information: Home page content : <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"> 
<head> 
<title>IIS 10.0 Detailed Error - 500.0 - Internal Server Error</title> 
<style type="text/css"> 
<!-- 
body{margin:0;font-size:.7em;font-family:Verdana,Arial,Helvetica,sans-serif;} 
code{margin:0;color:#006600;font-size:1.1em;font-weight:bold;} 
.config_source code{font-size:.8em;color:#000000;} 
pre{margin:0;font-size:1.4em;word-wrap:break-word;} 
ul,ol{margin:10px 0 10px 5px;} 
ul.first,ol.first{margin-top:5px;} 
fieldset{padding:0 15px 10px 15px;word-break:break-all;} 
.summary-container fieldset{padding-bottom:5px;margin-top:4px;} 
legend.no-expand-all{padding:2px 15px 4px 10px;margin:0 0 0 -12px;} 
legend{color:#333333;;margin:4px 0 8px -12px;_margin-top:0px; 
font-weight:bold;font-size:1em;} 
a:link,a:visited{color:#007EFF;font-weight:bold;} 
a:hover{text-decoration:none;} 
h1{font-size:2.4em;margin:0;color:#FFF;} 
h2{font-size:1.7em;margin:0;color:#CC0000;} 
h3{font-size:1.4em;margin:10px 0 0 0;color:#CC0000;} 
h4{font-size:1.2em;margin:10px 0 5px 0; 
}#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS",Verdana,sans-serif; 
 color:#FFF;background-color:#5C87B2; 
}#content{margin:0 0 0 2%;position:relative;} 
.summary-container,.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;} 
.content-container p{margin:0 0 10px 0; 
}#details-left{width:35%;float:left;margin-right:2%; 
}#details-right{width:63%;float:left;overflow:hidden; 
}#server_version{width:96%;_height:1px;min-height:1px;margin:0 0 5px 0;padding:11px 2% 8px 2%;color:#FFFFFF; 
 background-color:#5A7FA5;border-bottom:1px solid #C1CFDD;border-top:1px solid #4A6C8E;font-weight:normal; 
 font-size:1em;color:#FFF;text-align:right; 
}#server_version p{margin:5px 0;} 
table{margin:4px 0 4px 0;width:100%;border:none;} 
td,th{vertical-align:top;padding:3px 0;text-align:left;font-weight:normal;border:none;} 
th{width:30%;text-align:right;padding-right:2%;font-weight:bold;} 
thead th{background-color:#ebebeb;width:25%; 
}#details-right th{width:20%;} 
table tr.alt td,table tr.alt th{} 
.highlight-code{color:#CC0000;font-weight:bold;font-style:italic;} 
.clear{clear:both;} 
.preferred{padding:0 5px 2px 5px;font-weight:normal;background:#006633;color:#FFF;font-size:.8em;} 
--> 
</style> 
 
</head> 
<body> 
<div id="content"> 
<div class="content-container"> 
  <h3>HTTP Error 500.0 - Internal Server Error</h3> 
  <h4>There is a problem with the resource you are looking for, so it cannot be displayed.</h4> 
</div> 
<div class="content-container"> 
 <fieldset><h4>Most likely causes:</h4> 
  <ul>     <li>A module is referenced in configuration, but the module has not been installed or the name of the module is misspelled.</li>     <li>IIS received the request; however, an internal error occurred during the processing of the request. The root cause of this error depends on which module handles the request and what was happening in the worker process when this error occurred.</li>     <li>IIS was not able to access the web.config file for the Web site or application. This can occur if the NTFS permissions are set incorrectly.</li>     <li>IIS was not able to process configuration for the Web site or application.</li>     <li>The authenticated user does not have permission to use this DLL.</li> </ul> 
 </fieldset> 
</div> 
<div class="content-container"> 
 <fieldset><h4>Things you can try:</h4> 
  <ul>     <li>Verify that the module is installed. The error description may contain additional information to help you determine which module is causing the error.</li>     <li>If the module is installed, verify that the module name is not misspelled in the configuration/system.webServer/handlers config section.</li>     <li>Ensure that the NTFS permissions for the web.config file are correct and allow access to the Web server's machine account.</li>     <li>Check the event logs to see if any additional information was logged.</li>     <li>Verify the permissions for the DLL.</li>     <li>Check the failed request tracing logs for additional information about this error. For more information, click <a href="http://go.microsoft.com/fwlink/?LinkID=66439">here</a>. </li> </ul> 
 </fieldset> 
</div> 
 
<div class="content-container"> 
 <fieldset><h4>Detailed Error Information:</h4> 
  <div id="details-left"> 
   <table border="0" cellpadding="0" cellspacing="0"> 
    <tr class="alt"><th>Module</th><td>&nbsp;&nbsp;&nbsp;AspNetCoreModule</td></tr> 
    <tr><th>Notification</th><td>&nbsp;&nbsp;&nbsp;ExecuteRequestHandler</td></tr> 
    <tr class="alt"><th>Handler</th><td>&nbsp;&nbsp;&nbsp;aspNetCore</td></tr> 
    <tr><th>Error Code</th><td>&nbsp;&nbsp;&nbsp;0x8007000d</td></tr> 
     
   </table> 
  </div> 
  <div id="details-right"> 
   <table border="0" cellpadding="0" cellspacing="0"> 
    <tr class="alt"><th>Requested URL</th><td>&nbsp;&nbsp;&nbsp;http://localhost:63871/</td></tr> 
    <tr><th>Physical Path</th><td>&nbsp;&nbsp;&nbsp;C:\b\t\buildTmp\f5ee055e-7598-439f-934b-f85d0b4d3944</td></tr> 
    <tr class="alt"><th>Logon Method</th><td>&nbsp;&nbsp;&nbsp;Anonymous</td></tr> 
    <tr><th>Logon User</th><td>&nbsp;&nbsp;&nbsp;Anonymous</td></tr> 
    <tr class="alt"><th>Request Tracing Directory</th><td>&nbsp;&nbsp;&nbsp;C:\Users\asplab\Documents\IISExpress\TraceLogFiles\MUSICSTORETESTSITE</td></tr> 
   </table> 
   <div class="clear"></div> 
  </div> 
 </fieldset> 
</div> 
 
<div class="content-container"> 
 <fieldset><h4>More Information:</h4> 
  This error means that there was a problem while processing the request. The request was received by the Web server, but during processing a fatal error occurred, causing the 500 error. 
  <p><a href="https://go.microsoft.com/fwlink/?LinkID=62293&amp;IIS70Error=500,0,0x8007000d,9200">View more information &raquo;</a></p> 
  <p>Microsoft Knowledge Base Articles:</p> 
 <ul><li></li></ul> 
 
 </fieldset> 
</div> 
</div> 
</body> 
</html> 
| [2018-05-02T12:22:18] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: Attempting to cancel process 7364
| [2018-05-02T12:22:18] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress Process 7364 shut down
| [2018-05-02T12:22:18] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: Host process shutting down.
| [2018-05-02T12:22:18] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: Successfully terminated host process with process Id '7364'
| [2018-05-02T12:22:19] SmokeTestSuite Information: Trying to drop database 'MusicStore_Test_223a38d182ae4d44b0785cbd7320de9e'
| [2018-05-02T12:22:19] SmokeTestSuite Information: Successfully dropped database MusicStore_Test_223a38d182ae4d44b0785cbd7320de9e
| [2018-05-02T12:22:19] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: [Time]: Total time taken for this test variation '2.6017144' seconds
| [2018-05-02T12:22:19] TestLifetime Information: Finished test SmokeTestSuite_IISExpress_Portable in 2.6036391s
```

**Comment by ryanbrandenburg** [comment]
This error (or a similarly non-specific error) also affects [PublishAndRun_Test](http://aspnetci/viewLog.html?buildId=480731&tab=buildResultsDiv&buildTypeId=Lite_MusicStoreTest#testNameId4097536007154953380).

**Comment by ryanbrandenburg** [comment]
NtlmAuthenticationTest [failed again](http://aspnetci/viewLog.html?buildId=513796&buildTypeId=Lite_MusicStoreTest).

**Comment by ryanbrandenburg** [comment]
Smoke_Tests [failed again](http://aspnetci/viewLog.html?buildId=513798&buildTypeId=XPlat_Windows_Win10Universe).

**Comment by ryanbrandenburg** [comment]
Smoke_Tests [failed again](http://aspnetci/viewLog.html?buildId=513800&buildTypeId=XPlat_Windows_Win7_Universe).

**Comment by ryanbrandenburg** [comment]
OpenIdConnectTestSuite [failed again](http://aspnetci/viewLog.html?buildId=513794&buildTypeId=XPlat_Windows_Win8_Universe).

**Comment by ryanbrandenburg** [comment]
Smoke_Tests [failed again](http://aspnetci/viewLog.html?buildId=516957&buildTypeId=Releases_22xPublic_Win2012).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
Smoke_Tests [failed again](http://aspnetci/viewLog.html?buildId=517017&buildTypeId=Releases_22xPublic_Win2012).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
Smoke_Tests [failed again](http://aspnetci/viewLog.html?buildId=517196&buildTypeId=Releases_22xPublic_Win2012).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
Smoke_Tests [failed again](http://aspnetci/viewLog.html?buildId=517878&buildTypeId=XPlat_Windows_Win7_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
Smoke_Tests [failed again](http://aspnetci/viewLog.html?buildId=517986&buildTypeId=XPlat_Windows_Win2008r2_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
Smoke_Tests [failed again](http://aspnetci/viewLog.html?buildId=518163&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
Smoke_Tests [failed again](http://aspnetci/viewLog.html?buildId=518306&buildTypeId=Lite_MusicStore).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
Smoke_Tests [failed again](http://aspnetci/viewLog.html?buildId=518436&buildTypeId=Releases_22xPublic_Win2012).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
Smoke_Tests [failed again](http://aspnetci/viewLog.html?buildId=518392&buildTypeId=XPlat_Windows_Win8_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
Smoke_Tests [failed again](http://aspnetci/viewLog.html?buildId=518379&buildTypeId=XPlat_Windows_Win2008r2_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
Smoke_Tests [failed again](http://aspnetci/viewLog.html?buildId=518375&buildTypeId=XPlat_Windows_Win7_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
Smoke_Tests [failed again](http://aspnetci/viewLog.html?buildId=518373&buildTypeId=XPlat_Windows_Win10Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
Smoke_Tests [failed again](http://aspnetci/viewLog.html?buildId=518450&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
Smoke_Tests [failed again](http://aspnetci/viewLog.html?buildId=518510&buildTypeId=Releases_22xPublic_Win2012).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
Smoke_Tests [failed again](http://aspnetci/viewLog.html?buildId=518585&buildTypeId=Releases_22xPublic_Win2012).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
Smoke_Tests [failed again](http://aspnetci/viewLog.html?buildId=518699&buildTypeId=Releases_22xPublic_Win2012).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
Smoke_Tests [failed again](http://aspnetci/viewLog.html?buildId=518651&buildTypeId=XPlat_Windows_Win8_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
Smoke_Tests [failed again](http://aspnetci/viewLog.html?buildId=518638&buildTypeId=XPlat_Windows_Win2008r2_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
Smoke_Tests [failed again](http://aspnetci/viewLog.html?buildId=518634&buildTypeId=XPlat_Windows_Win7_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
Smoke_Tests [failed again](http://aspnetci/viewLog.html?buildId=518632&buildTypeId=XPlat_Windows_Win10Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
Smoke_Tests [failed again](http://aspnetci/viewLog.html?buildId=518926&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
Smoke_Tests [failed again](http://aspnetci/viewLog.html?buildId=518816&buildTypeId=XPlat_Windows_Win2008r2_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
Smoke_Tests [failed again](http://aspnetci/viewLog.html?buildId=518812&buildTypeId=XPlat_Windows_Win7_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
Smoke_Tests [failed again](http://aspnetci/viewLog.html?buildId=519073&buildTypeId=Releases_22xPublic_Win2012).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
Smoke_Tests [failed again](http://aspnetci/viewLog.html?buildId=519050&buildTypeId=XPlat_Windows_Win2008r2_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
Smoke_Tests [failed again](http://aspnetci/viewLog.html?buildId=519091&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
Smoke_Tests [failed again](http://aspnetci/viewLog.html?buildId=519046&buildTypeId=XPlat_Windows_Win7_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
PublishAndRun_Test [failed with about the same error](http://aspnetci/viewLog.html?buildId=531083&buildTypeId=Lite_UniverseTest) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
NtlmAuthenticationTest [failed with about the same error](http://aspnetci/viewLog.html?buildId=532093&buildTypeId=XPlat_Windows_Win8_Universe) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
NtlmAuthenticationTest [failed with about the same error](http://aspnetci/viewLog.html?buildId=533284&buildTypeId=XPlat_Windows_Win7_Universe) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
NtlmAuthenticationTest [failed with about the same error](http://aspnetci/viewLog.html?buildId=534200&buildTypeId=Lite_UniverseTest) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
DotnetRun_Tests [failed with about the same error](http://aspnetci/viewLog.html?buildId=552876&buildTypeId=XPlat_Mac_MacUniverseCoreCLR) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by mkArtakMSFT** [comment]
Thanks @ryanbrandenburg.
@dougbu, can you please fix this? Thanks!

**Comment by dougbu** [comment]
`DotnetRun_Tests` failure 18 hours ago ([above](https://github.com/aspnet/MusicStore/issues/848#issuecomment-420842757)) was a `RequestTimeout` with Kestrel. That failure looks very much like aspnet/KestrelHttpServer#2850 and I've therefore reopened the bug. @halter73 please confirm the fix for that bug was correctly merged into the `master` branch.

In particular, note the short period covered in the following logging:
```
| [36.737s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: Now listening on: http://127.0.0.1:63428
| [36.737s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: Application started. Press Ctrl+C to shut down.
| [36.738s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Application ready at URL: http://127.0.0.1:63428/
| [36.739s] DotnetRunTests Warning: Retry count 1..
| [38.208s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: \x1b[40m\x1b[32minfo\x1b[39m\x1b[22m\x1b[49m: Microsoft.AspNetCore.Server.Kestrel[17]
| [38.208s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout:       Connection id "0HLGP17B4BLVD" bad request data: "Reading the request headers timed out."
| [38.209s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Reading the request headers timed out.
```
 
----
On the other hand, the following error message shows up in the error page displayed in al of the other August failures I checked:
```
Cannot add duplicate collection entry of type 'add' with unique key attribute 'name' set to 'aspNetCore'
```
and all relate to deploying into IIS Express. The deployer has since changed significantly and it appears those failures are now resolved.

**Comment by dougbu** [comment]
@halter73 if you agree this is a variant of aspnet/KestrelHttpServer#2850, please take this issue. If not, please suggest where I should look instead.

/cc @davidfowl
