### ISSUE TITLE
Test failure: PublishAndRun_Test

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/MusicStore#868]
This test [fails](http://aspnetci/viewLog.html?buildId=557737&buildTypeId=XPlat_Windows_Win8_Universe) occasionally with the following error:
```
System.Net.Http.HttpRequestException : An error occurred while sending the request.
---- System.IO.IOException : Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.
-------- System.Net.Sockets.SocketException : An existing connection was forcibly closed by the remote host
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithNtAuthAsync(HttpRequestMessage request, Uri authUri, ICredentials credentials, Boolean isProxyAuth, HttpConnection connection, HttpConnectionPool connectionPool, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.IntegrationTesting.LoggingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.AspNetCore.Server.IntegrationTesting.RetryHelper.RetryRequest(Func`1 retryBlock, ILogger logger, CancellationToken cancellationToken, Int32 retryCount)
   at Microsoft.AspNetCore.Server.IntegrationTesting.RetryHelper.RetryRequest(Func`1 retryBlock, ILogger logger, CancellationToken cancellationToken, Int32 retryCount)
   at E2ETests.PublishAndRunTests.PublishAndRun_Test(TestVariant variant) in C:\BuildAgent\work\33bdfc1cae7b2a38\modules\MusicStore\test\MusicStore.E2ETests\PublishAndRunTests.cs:line 99
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
----- Inner Stack Trace -----
------- Stdout: -------
| [0.001s] TestLifetime Information: Starting test PublishAndRun_Test-Server: Kestrel, TFM: net461, Type: Standalone, Arch: x86 at 2018-09-20T19:32:20
| [0.001s] TestLifetime Information: Starting test PublishAndRunTests_Server: Kestrel, TFM: net461, Type: Standalone, Arch: x86 at 2018-09-20T19:32:20
| [0.001s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Deploying [Variation] :: ServerType=Kestrel, Runtime=Clr, Arch=x86, BaseUrlHint=, Publish=True
| [0.002s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Executing command dotnet publish  --output "C:\BuildAgent\temp\buildTmp\8149ef4bde60406596d1f7fbb79f7541" --framework net461 --configuration Release --no-restore -p:VerifyMatchingImplicitPackageVersion=false --runtime win7-x86 
| [0.234s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet-publish stdout: Microsoft (R) Build Engine version 15.8.166+gd4e8d81a88 for .NET Core
| [0.234s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet-publish stdout: Copyright (C) Microsoft Corporation. All rights reserved.
| [1.379s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet-publish stdout:   MusicStore -> C:\BuildAgent\work\33bdfc1cae7b2a38\modules\MusicStore\samples\MusicStore\bin\Release\net461\win7-x86\MusicStore.exe
| [1.385s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet-publish stdout:   MusicStore -> C:\BuildAgent\work\33bdfc1cae7b2a38\modules\MusicStore\samples\MusicStore\bin\Release\net461\win7-x86\MusicStore.Views.dll
| [2.265s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet-publish stdout:   MusicStore -> C:\BuildAgent\temp\buildTmp\8149ef4bde60406596d1f7fbb79f7541\
| [2.319s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet publish finished with exit code : 0
| [2.319s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Executing C:\BuildAgent\temp\buildTmp\8149ef4bde60406596d1f7fbb79f7541\MusicStore.exe  --urls http://127.0.0.1:0/ --server Microsoft.AspNetCore.Server.Kestrel
| [2.319s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Removing environment variable ASPNETCORE_ENVIRONMENT
| [2.319s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: SET ASPNETCORE_DETAILEDERRORS=true
| [2.319s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: SET Data__DefaultConnection__ConnectionString=Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=MusicStore_Test_105eb43764654e468242cd7cb511a4d4;Integrated Security=True;MultipleActiveResultSets=True;Connect Timeout=30
| [2.335s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Started C:\BuildAgent\temp\buildTmp\8149ef4bde60406596d1f7fbb79f7541\MusicStore.exe. Process Id : 12556
| [8.433s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: C:\BuildAgent\temp\buildTmp\8149ef4bde60406596d1f7fbb79f7541\MusicSt
...
```
Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

This test failed on master.

CC @mkArtakMSFT

This issue was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this actually a flaky test?
  * No, this is a regular test failure, fix the test/product (TODO: Link to commit/PR)
  * Yes, proceed below...

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * Is there any logging or extra information that we could add to make this more diagnosable when it happens again?
        * Yes?
            * [ ] Add the logging (TODO: Link to PR/commit)
        * No?
            * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
PublishAndRun_Test [failed with about the same error](http://aspnetci/viewLog.html?buildId=557737&buildTypeId=XPlat_Windows_Win8_Universe) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by mkArtakMSFT** [comment]
@pranavkm, can you please take a look at this? Thanks!

**Comment by pranavkm** [comment]
Seems like a Kestrel thing:

```
 System.IO.FileLoadException: Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
 File name: 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
    at System.Memory`1.op_Implicit(Memory`1 memory)
    at System.IO.Pipelines.BufferSegment.set_End(Int32 value)
    at System.IO.Pipelines.BufferSegment.SetMemory(IMemoryOwner`1 memoryOwner, Int32 start, Int32 end, Boolean readOnly)
    at System.IO.Pipelines.Pipe.AllocateWriteHeadUnsynchronized(Int32 sizeHint)
    at System.IO.Pipelines.Pipe.GetMemory(Int32 sizeHint)
    at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.<ProcessReceives>d__27.MoveNext()
```

Did we pick up a bad package?

**Comment by aspnet-hello** [comment]
OpenIdConnectTestSuite [failed with about the same error](http://aspnetci/viewLog.html?buildId=558038&buildTypeId=XPlat_Windows_Win8_Universe) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
This is the same issue as aspnet/Home#3544.

**Comment by aspnet-hello** [comment]
There were 8 failures [with about the same error](http://aspnetci/viewLog.html?buildId=558745&buildTypeId=Lite_UniverseTest) on master:
- PublishAndRun_Test
- PublishAndRun_Test
- PublishAndRun_Test
- PublishAndRun_Test
- PublishAndRun_Test
- OpenIdConnectTestSuite
- PublishAndRun_Test
- DotnetRun_Tests


This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
There were 8 failures [with about the same error](http://aspnetci/viewLog.html?buildId=559368&buildTypeId=XPlat_Windows_Win8_Universe) on master:
- PublishAndRun_Test
- OpenIdConnectTestSuite
- PublishAndRun_Test
- PublishAndRun_Test
- PublishAndRun_Test
- PublishAndRun_Test
- PublishAndRun_Test
- DotnetRun_Tests


This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
There were 8 failures [with about the same error](http://aspnetci/viewLog.html?buildId=560048&buildTypeId=XPlat_Windows_Win8_Universe) on master:
- OpenIdConnectTestSuite
- PublishAndRun_Test
- PublishAndRun_Test
- PublishAndRun_Test
- PublishAndRun_Test
- DotnetRun_Tests
- PublishAndRun_Test
- PublishAndRun_Test


This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
There were 8 failures [with about the same error](http://aspnetci/viewLog.html?buildId=560221&buildTypeId=XPlat_Windows_Win7_Universe) on master:
- OpenIdConnectTestSuite
- PublishAndRun_Test
- DotnetRun_Tests
- PublishAndRun_Test
- PublishAndRun_Test
- PublishAndRun_Test
- PublishAndRun_Test
- PublishAndRun_Test


This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
There were 8 failures [with about the same error](http://aspnetci/viewLog.html?buildId=561382&buildTypeId=Lite_UniverseTest) on master:
- PublishAndRun_Test
- PublishAndRun_Test
- PublishAndRun_Test
- PublishAndRun_Test
- OpenIdConnectTestSuite
- PublishAndRun_Test
- PublishAndRun_Test
- DotnetRun_Tests


This comment was made automatically. If there is a problem contact ryanbrandenburg.
