### ISSUE TITLE
Test failure: Smoke_Tests

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/MusicStore#870]
This issue was made automatically. If there is a problem contact ryanbrandenburg.

This test [failed](http://aspnetci/viewLog.html?buildId=567470&buildTypeId=XPlat_Windows_Win7_Universe) with the following error:

```
System.OperationCanceledException : Failed to connect, retry canceled.
   at Microsoft.AspNetCore.Server.IntegrationTesting.RetryHelper.RetryRequest(Func`1 retryBlock, ILogger logger, CancellationToken cancellationToken, Int32 retryCount)
   at E2ETests.SmokeTests.RunTestsAsync(DeploymentResult deploymentResult, ILogger logger) in C:\BuildAgent\work\33bdfc1cae7b2a38\modules\MusicStore\test\MusicStore.E2ETests\SmokeTests.cs:line 159
   at E2ETests.SmokeTests.Smoke_Tests(TestVariant variant) in C:\BuildAgent\work\33bdfc1cae7b2a38\modules\MusicStore\test\MusicStore.E2ETests\SmokeTests.cs:line 69
--- End of stack trace from previous location where exception was thrown ---
------- Stdout: -------
| [0.000s] TestLifetime Information: Starting test Smoke_Tests-Server: IISExpress, TFM: netcoreapp2.2, Type: Portable, Arch: x64, ANCM: V2, Host: InProcess at 2018-10-03T20:48:37
| [0.000s] TestLifetime Information: Starting test SmokeTestSuite_Server: IISExpress, TFM: netcoreapp2.2, Type: Portable, Arch: x64, ANCM: V2, Host: InProcess at 2018-10-03T20:48:37
| [0.001s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: Deploying [Variation] :: ServerType=IISExpress, Runtime=CoreClr, Arch=x64, BaseUrlHint=, Publish=False
| [0.001s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: Executing: dotnet C:\BuildAgent\work\33bdfc1cae7b2a38\modules\MusicStore\samples\MusicStore\bin\Release\netcoreapp2.2\MusicStore.dll
| [0.001s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: ContentRoot: C:\BuildAgent\work\33bdfc1cae7b2a38\modules\MusicStore\samples\MusicStore
| [0.001s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: Attempting to start IIS Express on port: 49880
| [0.005s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: Executing command : C:\Program Files\IIS Express\iisexpress.exe /site:HttpTestSite /config:C:\BuildAgent\temp\buildTmp\tmp3A1A.tmp /trace:error /systray:false
| [0.005s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: SET ASPNETCORE_ENVIRONMENT=SocialTesting
| [0.005s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: SET ASPNETCORE_DETAILEDERRORS=true
| [0.005s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: SET Data__DefaultConnection__ConnectionString=Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=MusicStore_Test_e2c9448d959c4471a1403336e4161e00;Integrated Security=True;MultipleActiveResultSets=True;Connect Timeout=30
| [0.005s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: SET LAUNCHER_PATH=dotnet
| [0.005s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: SET LAUNCHER_ARGS=C:\BuildAgent\work\33bdfc1cae7b2a38\modules\MusicStore\samples\MusicStore\bin\Release\netcoreapp2.2\MusicStore.dll
| [0.005s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: SET ASPNETCORE_CONTENTROOT=C:\BuildAgent\work\33bdfc1cae7b2a38\modules\MusicStore\samples\MusicStore
| [0.008s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress Process 18208 started
| [0.057s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: Starting IIS Express ...
| [0.070s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: Initializing the W3 Server Started CTC = 1772173843 
| [0.075s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: W3 Server initializing WinSock.  CTC = 1772173843 
| [0.075s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: W3 Server WinSock initialized.  CTC = 1772173843 
| [0.075s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: W3 Server ThreadPool initialized (ipm has signalled).  CTC = 1772173843 
| [0.093s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: Start listenerChannel http:0
| [0.093s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: Successfully registered URL "http://localhost:49880/" for site "HttpTestSite" application "/"
| [0.094s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: Registration completed for site "HttpTestSite"
| [0.094s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: AppPool 'IISExpressAppPool' initialized
| [0.094s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: InitComplete event signalled
| [0.094s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: IIS Express is running.
| [0.094s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: Started iisexpress successfully. Process Id : 18208, Port: 49880
| [0.094s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: Application ready at URL: http://localhost:49880/
| [0.094s] SmokeTestSuite Warning: Retry count 1..
| [10.976s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: IncrementMessages called
| [10.978s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: Request started: "GET" http://localhost:49880/
| [14.905s] System.Net.Http.HttpClient Error: Exception while sending 'GET http://localhost:49880/' : System.Threading.Tasks.TaskCanceledException: The operation was canceled. ---> System.IO.IOException: Unable to read data from the transport co
...
```

Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

This test failed on master.

CC @mkArtakMSFT

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this actually a flaky test?
  * No, this is a regular test failure, fix the test/product (TODO: Link to commit/PR)
  * Yes, proceed below...

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * Is there any logging or extra information that we could add to make this more diagnosable when it happens again?
        * Yes?
            * [ ] Add the logging (TODO: Link to PR/commit)
        * No?
            * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 1 failures [with about the same error](http://aspnetci/viewLog.html?buildId=571933&buildTypeId=XPlat_Windows_Win2008r2_Universe) on master at 8:04:51 PM:
- Smoke_Tests

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 1 failures [with about the same error](http://aspnetci/viewLog.html?buildId=572655&buildTypeId=XPlat_Windows_Win7_Universe) on master at 10:53:03 AM:
- Smoke_Tests

**Comment by muratg** [comment]
@JunTaoLuo please take a look _after_ any preview3 work. Thanks!

**Comment by jkotalik** [comment]
@muratg this is an InProc issue... we should probably investigate.
