### ISSUE TITLE
Test failure: PublishAndRun_Test

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/MusicStore#876]
This issue was made automatically. If there is a problem contact ryanbrandenburg.

This test [failed](http://aspnetci/viewLog.html?buildId=588636&buildTypeId=XPlat_Windows_Win2008r2_Universe) with the following error:

```
Assert.Equal() Failure
Expected: OK
Actual:   BadGateway
   at E2ETests.Validator.VerifyHomePage(HttpResponseMessage response, Boolean useNtlmAuthentication) in C:\BuildAgent\work\e37dd45d8cd1eaf4\modules\MusicStore\test\MusicStore.E2ETests\Implementation\Validator.cs:line 94
   at E2ETests.PublishAndRunTests.PublishAndRun_Test(TestVariant variant) in C:\BuildAgent\work\e37dd45d8cd1eaf4\modules\MusicStore\test\MusicStore.E2ETests\PublishAndRunTests.cs:line 81
--- End of stack trace from previous location where exception was thrown ---
------- Stdout: -------
| [0.005s] TestLifetime Information: Starting test PublishAndRun_Test-Server: IISExpress, TFM: netcoreapp3.0, Type: Portable, Arch: x86, ANCM: V2, Host: OutOfProcess at 2018-11-06T11:11:48
| [0.001s] TestLifetime Information: Starting test PublishAndRunTests_Server: IISExpress, TFM: netcoreapp3.0, Type: Portable, Arch: x86, ANCM: V2, Host: OutOfProcess at 2018-11-06T11:11:48
| [0.002s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: Deploying [Variation] :: ServerType=IISExpress, Runtime=CoreClr, Arch=x86, BaseUrlHint=, Publish=True
| [0.002s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: Executing command dotnet publish  --output "C:\BuildAgent\temp\buildTmp\c752a86b27bf44d48ee0e55d55bd10b5" --framework netcoreapp3.0 --configuration Release --no-restore -p:VerifyMatchingImplicitPackageVersion=false 
| [0.254s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: dotnet-publish stdout: Microsoft (R) Build Engine version 15.9.19+g938f3292a0 for .NET Core
| [0.254s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: dotnet-publish stdout: Copyright (C) Microsoft Corporation. All rights reserved.
| [0.735s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: dotnet-publish stdout: C:\BuildAgent\work\e37dd45d8cd1eaf4\.dotnet\x64\sdk\3.0.100-preview-009730\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(142,5): message NETSDK1057: You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview [C:\BuildAgent\work\e37dd45d8cd1eaf4\modules\MusicStore\samples\MusicStore\MusicStore.csproj]
| [1.056s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: dotnet-publish stdout:   MusicStore -> C:\BuildAgent\work\e37dd45d8cd1eaf4\modules\MusicStore\samples\MusicStore\bin\Release\netcoreapp3.0\MusicStore.dll
| [1.057s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: dotnet-publish stdout:   MusicStore -> C:\BuildAgent\work\e37dd45d8cd1eaf4\modules\MusicStore\samples\MusicStore\bin\Release\netcoreapp3.0\MusicStore.Views.dll
| [1.774s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: dotnet-publish stdout:   MusicStore -> C:\BuildAgent\temp\buildTmp\c752a86b27bf44d48ee0e55d55bd10b5\
| [1.814s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: dotnet publish finished with exit code : 0
| [1.815s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: Attempting to start IIS Express on port: 53041
| [1.818s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug: Saving Config to C:\BuildAgent\temp\buildTmp\tmp7B34.tmp
| [1.819s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: Executing command : C:\Program Files (x86)\IIS Express\iisexpress.exe /site:HttpTestSite /config:C:\BuildAgent\temp\buildTmp\tmp7B34.tmp /trace:error /systray:false
| [1.819s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: Removing environment variable ASPNETCORE_ENVIRONMENT
| [1.820s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: SET ASPNETCORE_DETAILEDERRORS=true
| [1.820s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: SET Data__DefaultConnection__ConnectionString=Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=MusicStore_Test_7ae17bb6dc3940549ef6a39affb83c7d;Integrated Security=True;MultipleActiveResultSets=True;Connect Timeout=30
| [1.824s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress Process 14500 started
| [1.885s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: Starting IIS Express ...
| [1.900s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: Initializing the W3 Server Started CTC = 1817082765 
| [1.905s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: W3 Server initializing WinSock.  CTC = 1817082765 
| [1.905s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: W3 Server WinSock initialized.  CTC = 1817082765 
| [1.905s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: W3 Server ThreadPool initialized (ipm has signalled).  CTC = 1817082765 
| [1.931s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: Start listenerChannel http:0
| [1.932s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: Successfully registered URL "http://localhost:53041/" for site "HttpTestSite" application "/"
| [1.932s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: Registration completed for site "HttpTestSite"
| [1.932s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: AppPool 'IISExpressAppPool' initialized
| [1.932s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpr
...
```

Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

This test failed on master.

CC mkArtakMSFT

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this actually a flaky test?
  * No, this is a regular test failure, fix the test/product (TODO: Link to commit/PR)
  * Yes, proceed below...

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * Is there any logging or extra information that we could add to make this more diagnosable when it happens again?
        * Yes?
            * [ ] Add the logging (TODO: Link to PR/commit)
        * No?
            * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 4 failures [with about the same error](http://aspnetci/viewLog.html?buildId=588636&buildTypeId=XPlat_Windows_Win2008r2_Universe) on master at 1:31:38 AM:
- PublishAndRun_Test
- PublishAndRun_Test
- PublishAndRun_Test
- PublishAndRun_Test

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 5 failures [with about the same error](http://aspnetci/viewLog.html?buildId=588949&buildTypeId=XPlat_Windows_Win10Universe) on master at 1:15:09 PM:
- PublishAndRun_Test
- PublishAndRun_Test
- PublishAndRun_Test
- PublishAndRun_Test
- PublishAndRun_Test

**Comment by aspnet-hello** [comment]
This comment was made automatically. If there is a problem contact ryanbrandenburg.

There were 1 failures [with about the same error](http://aspnetci/viewLog.html?buildId=589993&buildTypeId=XPlat_Windows_Win2008r2_Universe) on master at 9:39:01 AM:
- Smoke_Tests
